# Generated by Django 2.2.11 on 2020-06-27 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Name_of_his_company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_name', models.CharField(blank=True, max_length=100, null=True)),
                ('N_price', models.IntegerField(blank=True, null=True)),
                ('N_quantity', models.IntegerField(blank=True, null=True)),
                ('N_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('N_supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_madical.Person_information')),
            ],
        ),
    ]
