# Generated by Django 2.2.11 on 2020-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0002_instock_person_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_information',
            name='Type_of_organization',
            field=models.CharField(choices=[('Company', 'Company'), ('Trader', 'Trader'), ('Wholeseller', 'Wholeseller'), ('Broker', 'Broker'), ('Other', 'Other')], default='Company', max_length=50),
        ),
    ]
