# Generated by Django 2.2.11 on 2020-08-02 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0014_auto_20200802_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='N_data',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 15, 16, 37, 930817), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 15, 16, 37, 930321), null=True),
        ),
    ]
