# Generated by Django 2.2.11 on 2020-08-04 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_madical', '0018_auto_20200804_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='product_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 4, 14, 5, 32, 514419), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='M_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 4, 14, 5, 32, 513913), null=True),
        ),
    ]
